steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend:latest'
      - '-f'
      - 'backend/Dockerfile' 

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID//backend:$SHORT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-west1' 
      - '--allow-unauthenticated' 
images:
  - 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/backend:latest'
options:
  logging: NONE

