steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      build -t us-west1-docker.pkg.dev/$PROJECT_ID/bake-off/backend -f backend/Dockerfile .
    automapSubstitutions: true
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/bake-off/backend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-west11' 
      - '--allow-unauthenticated' 
images:
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/bake-off/backend'
